export const META_ANALYSIS_PIPELINE_SKILLS = [
  'meta-pipeline-planner',
  'meta-analysis-workflow',
] as const;

export const META_ANALYSIS_ROUTER_SKILLS = [
  'meta-analysis-workflow',
] as const;

export const META_ANALYSIS_STAGE_SKILLS = {
  literature: [
    'meta-analysis-workflow',
    'literature-review',
    'pubmed-search-strategy',
    'pubmed-database',
    'citation-management',
    'scientific-critical-thinking',
  ],
  protocol: [
    'meta-analysis-workflow',
    'literature-review',
    'scientific-critical-thinking',
  ],
  ideation: [
    'meta-analysis-workflow',
    'scientific-brainstorming',
    'hypothesis-generation',
    'scientific-critical-thinking',
    'literature-review',
    'pubmed-search-strategy',
    'pubmed-database',
  ],
  scopingReview: [
    'meta-analysis-workflow',
    'literature-review',
    'pubmed-search-strategy',
    'pubmed-database',
    'citation-management',
    'scientific-critical-thinking',
  ],
  searchDedupe: [
    'meta-analysis-workflow',
    'pubmed-search-strategy',
    'citation-management',
  ],
  pdfAcquisition: [
    'meta-analysis-workflow',
    'meta-zotero-fulltext-handoff',
    'zotero-medautodata-library',
    'citation-management',
  ],
  titleAbstractFirstScreen: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
  ],
  titleAbstractSecondScreen: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  titleAbstractScreening: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  fullTextDownload: [
    'meta-analysis-workflow',
    'paper-lookup',
    'paper-fetcher',
    'research-paper-downloader',
    'paper-download',
    'legal-pdf-acquisition',
    'public-literature-download',
    'citation-management',
  ],
  fullTextFirstScreen: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  fullTextSecondScreen: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  fullTextScreening: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  manualScreening: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'peer-review',
    'citation-management',
  ],
  screeningRescreen: [
    'meta-analysis-workflow',
    'meta-screening-rescreen',
    'citation-management',
    'peer-review',
  ],
  mineruParse: [
    'meta-analysis-workflow',
    'mineru-pdf-parser',
    'data-transform',
  ],
  extractionQuality: [
    'meta-analysis-workflow',
    'meta-extraction',
    'pdf-evidence-extraction',
    'diagnostic-data-extraction',
    'data-transform',
    'scientific-critical-thinking',
    'peer-review',
  ],
  qualityAssessment: [
    'meta-analysis-workflow',
    'scientific-critical-thinking',
    'peer-review',
    'data-transform',
  ],
  statistics: [
    'meta-analysis-workflow',
    'diagnostic-meta-analysis',
    'meta-statistics-r',
    'statistical-analysis',
    'data-stats-analysis',
    'statsmodels',
  ],
  figures: [
    'meta-analysis-workflow',
    'data-visualization-biomedical',
    'scientific-visualization',
    'data-viz-plots',
    'matplotlib',
    'seaborn',
    'plotly',
  ],
  manuscript: [
    'meta-analysis-workflow',
    'prisma-manuscript-writer',
    'manuscript-editor',
    'inno-paper-writing',
    'scientific-writing',
    'citation-management',
    'venue-templates',
    'docx',
  ],
  promotion: [
    'meta-analysis-workflow',
    'scientific-slides',
    'making-academic-presentations',
    'paper-2-web',
  ],
} as const;

export const META_ANALYSIS_SYNTHESIS_TYPE_SKILLS = {
  diagnostic: [
    'meta-analysis-workflow',
    'diagnostic-meta-analysis',
    'diagnostic-data-extraction',
    'meta-statistics-r',
    'statistical-analysis',
    'statsmodels',
    'data-transform',
    'data-visualization-biomedical',
  ],
  intervention: [
    'meta-analysis-workflow',
    'statistical-analysis',
    'data-stats-analysis',
    'statsmodels',
    'data-transform',
  ],
  prognostic: [
    'meta-analysis-workflow',
    'statistical-analysis',
    'statsmodels',
    'scikit-survival',
    'data-transform',
  ],
  prevalence: [
    'meta-analysis-workflow',
    'statistical-analysis',
    'data-stats-analysis',
    'statsmodels',
  ],
  network: [
    'meta-analysis-workflow',
    'statistical-analysis',
    'data-transform',
    'scientific-critical-thinking',
  ],
} as const;

export const META_ANALYSIS_SHORTCUT_SKILLS = [
  'meta-pipeline-planner',
  'meta-analysis-workflow',
  'pubmed-search-strategy',
  'meta-screening-rescreen',
  'legal-pdf-acquisition',
  'public-literature-download',
  'meta-zotero-fulltext-handoff',
  'mineru-pdf-parser',
  'meta-extraction',
  'pdf-evidence-extraction',
  'diagnostic-data-extraction',
  'diagnostic-meta-analysis',
  'meta-statistics-r',
  'prisma-manuscript-writer',
  'manuscript-editor',
] as const;
